FROM fedora:latest

RUN dnf update -y

RUN dnf install -y sudo dialog vim zsh curl wget git sl ruby automake gcc gcc-c++ kernel-devel fontconfig passwd htop

RUN dnf update -y

WORKDIR /root

COPY install.sh ./

RUN ./install.sh

RUN pip install trash-cli
