FROM fedora:latest

RUN dnf install -y sudo curl git zsh passwd \
 && dnf clean all

WORKDIR /root

COPY . /root/.dotfiles

RUN curl -fsSL https://get.chezmoi.io | sh -s -- -b /usr/local/bin \
 && chezmoi init --apply --source=/root/.dotfiles

CMD ["/usr/bin/zsh"]
